// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuPdoZnxrLZIDS5csXVF9RIaImVz9SLuI',
    appId: '1:243745039358:web:f08284f95eb3e2e27bd6af',
    messagingSenderId: '243745039358',
    projectId: 'chatapp-c785d',
    authDomain: 'chatapp-c785d.firebaseapp.com',
    storageBucket: 'chatapp-c785d.appspot.com',
    measurementId: 'G-4VSE9JL76K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCK9WIMKeHFLSGgjFhs6iHb40Xty_OZbE',
    appId: '1:243745039358:android:6ba32a081e58e3187bd6af',
    messagingSenderId: '243745039358',
    projectId: 'chatapp-c785d',
    storageBucket: 'chatapp-c785d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH3bgXY72r6umTnB8o55gv-dRLlu_iEmg',
    appId: '1:243745039358:ios:f55295fee07c5fad7bd6af',
    messagingSenderId: '243745039358',
    projectId: 'chatapp-c785d',
    storageBucket: 'chatapp-c785d.appspot.com',
    iosClientId: '243745039358-jil17g3eu9b43acqo2bjcagnb294f2kl.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH3bgXY72r6umTnB8o55gv-dRLlu_iEmg',
    appId: '1:243745039358:ios:f55295fee07c5fad7bd6af',
    messagingSenderId: '243745039358',
    projectId: 'chatapp-c785d',
    storageBucket: 'chatapp-c785d.appspot.com',
    iosClientId: '243745039358-jil17g3eu9b43acqo2bjcagnb294f2kl.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
